name: jikgwan

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - 3030:3030
    environment:
      - DB_HOST=jikgwan-postgres
      - DATABASE_URL=postgresql://postgres:1234@jikgwan-postgres:5432/jikgwan
    env_file:
      - ./apps/backend/secret/.env
    networks:
      - jikgwan-net

networks:
  jikgwan-net:
    external: true
    name: jikgwan-net
