import type { Metadata } from 'next';
import Providers from './providers';
import '@/shared/styles/index.css';
import 'sonner/dist/styles.css';
import Header from '@/shared/ui/header/header';
import Footer from '@/shared/ui/footer/footer';
import '@/mocks'; // MSW 초기화 (브라우저 환경에서만 동작)

export const metadata: Metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Header />
            <div className="max-w-[1440px] mx-auto w-full flex-1">
              <main>{children}</main>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
