import type { Metadata } from 'next';
import Providers from './providers';
import '@/shared/styles/index.css';
import Header from '@/shared/ui/header/header';
import '@/mocks'; // MSW 초기화 (브라우저 환경에서만 동작)

export const metadata: Metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1440px] mx-auto">
          <Header />
          <main>
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
